[package]
name = "rinee"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
futures = "0.3.30"
sha2 = "0.10.8"
