[package]
name = "rinee"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread", "time"] }
